version: '3.8'

services:
  bank1:
    build: ./bank-server
    container_name: bank1
    environment:
      - BANK_NAME=Bank1
    ports:
      - "5001:5000"

  bank2:
    build: ./bank-server
    container_name: bank2
    environment:
      - BANK_NAME=Bank2
    ports:
      - "5002:5000"

  swift:
    build: ./swift-server
    container_name: swift
    ports:
      - "5003:5000"
